---
name: latest-amd64
kind: pipeline
type: docker
platform:
  arch: amd64
  os: linux
steps:
  - name: publish
    environment:
      arch: amd64
      os: linux
      eu: eouth
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_repository
      tags: [latest-amd64]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
trigger:
  branch:
    - master
---
name: latest-arm64
kind: pipeline
type: docker
platform:
  arch: arm64
  os: linux
steps:
  - name: publish
    image: plugins/docker
    settings:
      repo:
        from_secret: docker_repository
      tags: [latest-arm64]
      # auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
trigger:
  branch:
    - master
---
name: manifest
kind: pipeline
type: docker
depends_on:
  - latest-amd64
  - latest-arm64
steps:
  - name: publish-manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: p3000/skycapp-fhir-stack-controller:latest
      # template: foo/bar:v1.0.0-OS-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
 